---
abstract: 'Get track listings for BBC radio programmes'
author:
  - 'Adam Taylor <ajct@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-BBC-TrackListings
requires:
  FindBin::libs: 0
  Moose: 0
  URI: 0
  Web::Scraper: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/adamtaylor/www-bbc-tracklistings.git
version: 0.01
